before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
language: java
jdk: openjdk11
sudo: false
script: mvn clean verify
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  # Set up git user name and tag this commit
  - git config --local user.name "$GH_NAME"
  - git config --local user.email "$GH_MAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  - provider: releases
    api_key: "$GH_TOKEN"
    file: 
      - scenic-view/target/ScenicView-$project_version.jar
    skip_cleanup: true
    on:
      repo: xardif/scenic-view
    name: $project_version
