before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
language: java
jdk: openjdk11
sudo: false
script: mvn clean verify
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  - provider: releases
    api_key: "$GH_TOKEN"
    file: 
      - scenic-view/target/ScenicView-$project_version.jar
    skip_cleanup: true
    on:
      repo: xardif/scenic-view
    name: $project_version
