language: java
jdk: oraclejdk11
sudo: false
script: mvn clean verify
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: 
    - "target/ScenicView-11.0.0.jar"
  skip_cleanup: true
  on:
    repo: xardif/scenic-view
  name: $project_version
