# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6-jdk-11

pipelines:
  default:
    #- step:
    #    caches:
    #      - maven
    #    script: # Modify the commands below to build your repository.
    #      - mvn -B verify # -B batch mode makes Maven less verbose
    - step:
        name: Deploy to production
        deployment: production   # can be test, staging or production.
        # trigger: manual  # Uncomment to make this a manual deployment.
        caches:
          - maven
        script:
          - mvn -B verify
          - echo "Deploying to test environment"
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/ScenicView-11.0.0.jar"
